# Generated by Django 2.2.5 on 2020-02-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0003_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
