# Generated by Django 2.2.5 on 2020-02-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_collector', '0004_delete_examplemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='hotel_Main_Img',
            new_name='class_img',
        ),
    ]
